### ISSUE TITLE
Erreur compilation

### ISSUE THREAD

**Issue by xekil** [myfp31/Pronote2HomeassistantAppdaemon.#2]
Bonjour, 

Merci pour le partage, j'ai suivi scrupuleusement la procédure et je rencontre une erreur lors de la compilation du script.

L'interface WEB de Appdeamon indique :
`get_data | compile_error | 0 | 0 | {"module": "pronote", "class": "get_data"}`

Logs AppDaemon: 
```
2022-09-15 10:22:54.339172 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/pronote.py
2022-09-15 10:22:54.346142 WARNING AppDaemon: Unexpected error loading module: /config/appdaemon/apps/pronote.py:
2022-09-15 10:22:54.346517 WARNING AppDaemon: Removing associated apps:
2022-09-15 10:22:54.346900 WARNING AppDaemon: pronote
```

Est il possible de poster l'intégralement du script a utiliser ?

PS : Je me connect via educonnect, donc pas de problème avec les ENT

Au passage, un question concernant le port qu'il faut modifier dans le fichier configuration.yaml, il faut aussi modifier l'URL non ?
Si oui, quel est le chemin exact ? 

Merci.

**Comment by xekil** [comment]
J'avance un peu, j'ai identifié une erreur d'indentation dans le tuto, concernant le fichier pronote.yaml :   

```
---
pronote:
  module: pronote
  class: get_data
```
Maintenant les logs m'annonce :

`TypeError: 'list' object is not callable`

```
2022-09-15 13:34:10.569926 WARNING Error: ------------------------------------------------------------
2022-09-15 13:34:10.570293 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/pronote.py:
2022-09-15 13:34:10.570659 WARNING Error: ------------------------------------------------------------
2022-09-15 13:34:10.572606 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 993, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 784, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/appdaemon/apps/pronote.py", line 254, in <module>
    absences = client.current_period.absences()
TypeError: 'list' object is not callable

2022-09-15 13:34:10.572957 WARNING Error: ------------------------------------------------------------
```

Une idée ?
Merci

**Comment by xekil** [comment]
Solution trouvé, il faut supprimer les () à la fin de la ligne currentperiod.absence du script original :)

https://github.com/dathosim/Pronote2Homeassistant/issues/11

**Comment by myfp31** [comment]
Bonjour,
Merci pour les remontés, je vais corriger et désolé du temps de réponse.

**Comment by xekil** [comment]
Pas de quoi, merci encore pour le partage :)
